### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by coogor** [Tilka/fingerprint-gui#3]
Hi, I tried to compile your code against a recent version of QT, and it fails with:
[    4s] g++ -c -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fno-strict-aliasing -O2 -D_REENTRANT -Wall -Wextra -fPIC -DLIBEXECDIR=\"/usr/lib/fingerprint-gui\" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -I../../include -I../../upek/include -isystem /usr/include/qt5/Qca-qt5/QtCrypto -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o GlobalsImg.o ../../src/GlobalsImg.cpp
[    9s] In file included from /usr/include/qt5/QtCore/qobject.h:46,
[    9s]                  from /usr/include/qt5/QtCore/qabstractanimation.h:43,
[    9s]                  from /usr/include/qt5/QtCore/QtCore:6,
[    9s]                  from /usr/include/qt5/QtWidgets/QtWidgetsDepends:3,
[    9s]                  from /usr/include/qt5/QtWidgets/QtWidgets:3,
[    9s]                  from ../../src/GlobalsImg.cpp:1:
[    9s] /usr/include/glib-2.0/gio/gdbusintrospection.h:155:25: error: expected unqualified-id before 'public'
[    9s]   155 |   GDBusSignalInfo     **signals;
[    9s]       |                         ^~~~~~~
[    9s] make[2]: *** [Makefile:737: GlobalsImg.o] Error 1

Full error log: https://build.opensuse.org/package/live_build_log/home:DocB:branches:hardware/fingerprint-gui/openSUSE_Tumbleweed/x86_64

**Comment by Tilka** [comment]
Please contact the original author or someone who maintains this software.
